# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-03 05:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20160706_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date_add',)},
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
