# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20160627_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date_pub',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date published'),
        ),
    ]
